apps/funcionarios/urls.py
from django.urls import path
from apps.funcionarios.views import (
    FuncionarioList,
    FuncionarioEdit,
    FuncionarioDelete,
    FuncionarioCreate)

urlpatterns = [
    path('list', FuncionarioList.as_view(), name='funcionario_list'),
    path('create', FuncionarioCreate.as_view(), name='funcionario_create'),
    path('edit/<int:pk>', FuncionarioEdit.as_view(), name='funcionario_edit'),
    path('delete/<int:pk>', FuncionarioDelete.as_view(), name='funcionario_delete'),
    
]

gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.core.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('horas-extras/', include('apps.registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/documentos/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario


class Documento(models.Model):
    descricao = models.CharField(max_length=100, help_text='Descrição do documento')
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')
    
    def get_absolute_url(self):
        return reverse('funcionario_edit', args=[self.pertence_id])
    
    def __str__(self):
        return self.descricao

apps/funcionarios/models.py
from django.db import models

from django.contrib.auth.models import User
from django.urls import reverse

from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa


class Funcionario(models.Model):
    """Manutenção do Cadastro de Funcionários"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=100, help_text='Nome do funcionário')
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(Empresa, models.PROTECT, null=True, blank=True)
    
    def __str__(self):
        return self.nome

    @staticmethod
    def get_absolute_url():
        return reverse('funcionario_list')

apps/funcionarios/views.py
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    UpdateView,
    DeleteView,
    CreateView)

from apps.funcionarios.models import Funcionario


class FuncionarioList(ListView):
    """Lista os Funcionários da empresa logada"""
    model = Funcionario
    
    def get_queryset(self):
        """Pega a empresa logada a partir do Usuário logado """
        empresa_logada = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa_logada)


class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamentos']


class FuncionarioCreate(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos']
    success_url = reverse_lazy('funcionario_list')
    
    def form_valid(self, form):
        funcionario = form.save(commit=False)
        funcionario.empresa = self.request.user.funcionario.empresa
        username = funcionario.nome.split(' ')[0] + funcionario.nome.split(' ')[1]
        funcionario.user = User.objects.create(username=username)
        funcionario.save()
        return super(FuncionarioCreate, self).form_valid(form)


class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('funcionario_list')

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}

{% block main %}
    <form method="post">{% csrf_token %}
        <h1>Tem certeza que quer apagar o registro de "{{ object }}"?</h1>
        <input class="btn btn-outline-danger" a type="submit" value="Confirma">
        <a href="{% url 'funcionario_list' %}" class="btn btn-primary">Voltar</a>
    </form>
{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
    {% if object %}
        <h1>Atualiza funcionário</h1>
    {% else %}
        <h1>Cria Novo funcionário</h1>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {{ form|bootstrap }}

        {% if object %}
            <button class="btn btn-outline-primary">Atualizar</button>
        {% else %}
            <button class="btn btn-outline-primary">Gravar</button>
        {% endif %}

    </form>
    <br>

    {% if object %}
    <a href="{% url 'documento_create' object.id %}"
       class="btn btn-outline-success">Adicionar Documento
    </a>
    {% endif %}

    {% if object.documento_set.all %}
<hr>
        <h5>Documentos em Anexo</h5>
        <ul>
        {% for documento in object.documento_set.all %}
            <li>
                <a href="{{ documento.arquivo.url }}">
                {{ documento }}
                </a>
            </li>
        {% endfor %}
        </ul>
    {% endif %}

{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}

{% block main %}
    <h1>Lista de Funcionários</h1>
    <a class="btn btn-info" href="{% url 'funcionario_create' %}">Novo funcionário</a>
    <table class="table table-striped table-hover">
        <thead>
            <th>Nome</th>
            <th>Ação</th>
        </thead>
        <tbody>
        {% for funcionario in object_list %}
            <tr>
                <td>
                    <a href="{% url 'funcionario_edit' funcionario.id %}">
                        {{ funcionario.nome }}
                    </a>
                </td>
                <td>
                    <a href="{% url 'funcionario_delete' funcionario.id %}">
                        Delete
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}